const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const state={followers:new Set(),following:new Set(),views:{},current:"notFollowingBack"};
const labels={followers:["Seguidores","Cuentas que te siguen"],following:["Seguidos","Cuentas que seguís"],mutual:["Seguimiento mutuo","Se siguen entre sí"],notFollowingBack:["No te siguen","Los seguís, pero no te siguen"],youDontFollow:["No los seguís","Te siguen, pero vos no los seguís"]};
const normalize=u=>String(u||"").trim().replace(/^@/,"").replace(/\/$/,"").toLowerCase();const fromHref=h=>{const m=String(h||"").match(/instagram\.com\/(?:_u\/)?([^/?#]+)/i);return m?normalize(m[1]):""};
function jsonUsers(data){const out=new Set();const walk=n=>{if(Array.isArray(n)){n.forEach(walk);return}if(!n||typeof n!=="object")return;if(Array.isArray(n.string_list_data))n.string_list_data.forEach(x=>{const u=normalize(x?.value)||fromHref(x?.href);if(u)out.add(u)});Object.values(n).forEach(walk)};walk(data);return out}
function htmlUsers(text){const out=new Set(),doc=new DOMParser().parseFromString(text,"text/html");doc.querySelectorAll("a").forEach(a=>{const u=fromHref(a.href)||normalize(a.textContent);if(u&&/^[a-z0-9._]+$/i.test(u))out.add(u)});return out}
function kindFor(name){const base=name.toLowerCase().split(/[\\/]/).pop();if(/^followers(?:_\d+)?\.(json|html)$/.test(base))return"followers";if(/^following\.(json|html)$/.test(base))return"following";return""}
function parseEntry(name,text){const kind=kindFor(name);if(!kind)return null;try{return{kind,users:name.toLowerCase().endsWith(".json")?jsonUsers(JSON.parse(text)):htmlUsers(text)}}catch(e){throw new Error("No pude leer "+name+": "+e.message)}}
async function processFiles(files){$("#status").textContent="Analizando archivos…";const found={followers:new Set(),following:new Set()};try{for(const file of files){if(file.name.toLowerCase().endsWith(".zip")){if(!window.JSZip)throw new Error("No se cargó el lector ZIP.");const zip=await JSZip.loadAsync(file);for(const [name,entry] of Object.entries(zip.files)){if(entry.dir||!kindFor(name))continue;const parsed=parseEntry(name,await entry.async("text"));parsed?.users.forEach(u=>found[parsed.kind].add(u))}}else{const parsed=parseEntry(file.name,await file.text());parsed?.users.forEach(u=>found[parsed.kind].add(u))}}if(!found.followers.size&&!found.following.size)throw new Error("No encontré followers_*.json/html ni following.json/html en la selección.");state.followers=found.followers;state.following=found.following;buildViews();$("#results").hidden=false;$("#status").textContent="Listo. Todo se procesó localmente en este navegador.";selectView("notFollowingBack")}catch(e){$("#status").textContent="Error: "+e.message}}
function buildViews(){const F=state.followers,G=state.following,diff=(a,b)=>[...a].filter(x=>!b.has(x)),inter=[...F].filter(x=>G.has(x));state.views={followers:[...F],following:[...G],mutual:inter,notFollowingBack:diff(G,F),youDontFollow:diff(F,G)};$("#nFollowers").textContent=F.size;$("#nFollowing").textContent=G.size;$("#nMutual").textContent=inter.length;$("#nNotBack").textContent=state.views.notFollowingBack.length;$("#nYouDont").textContent=state.views.youDontFollow.length}
function selectView(view){state.current=view;$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));const [t,n]=labels[view];$("#viewTitle").textContent=t;$("#viewNote").textContent=n;$("#search").value="";render()}
function render(){const q=normalize($("#search").value),rows=(state.views[state.current]||[]).filter(u=>u.includes(q)).sort((a,b)=>a.localeCompare(b));const list=$("#list");list.textContent="";if(!rows.length){const e=document.createElement("div");e.className="empty";e.textContent="No hay cuentas para mostrar.";list.append(e);return}rows.forEach(u=>{const row=document.createElement("div"),a=document.createElement("a"),s=document.createElement("span");row.className="person";a.href="https://www.instagram.com/"+encodeURIComponent(u)+"/";a.target="_blank";a.rel="noopener noreferrer";a.textContent="@"+u;s.textContent="Abrir en Instagram ↗";row.append(a,s);list.append(row)})}
function exportCsv(){const rows=(state.views[state.current]||[]).slice().sort(),csv=["usuario","\""+rows.join("\"\n\"")+"\""].join("\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="instagrameamo-"+state.current+".csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$("#pick").onclick=()=>$("#files").click();$("#files").onchange=e=>processFiles(e.target.files);$("#search").oninput=render;$("#csv").onclick=exportCsv;$$("[data-view]").forEach(b=>b.onclick=()=>selectView(b.dataset.view));
const drop=$("#drop");["dragenter","dragover"].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add("drag")}));["dragleave","drop"].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove("drag")}));drop.addEventListener("drop",e=>processFiles(e.dataTransfer.files));