const assert=require("node:assert/strict"),p=require("../parser.js");
const entry=(u)=>({string_list_data:[{href:"https://www.instagram.com/"+u+"/",value:u}]});
const followers=JSON.stringify([entry("ana"),entry("Beto"),entry("carla")]);
const following=JSON.stringify({relationships_following:[entry("beto"),entry("carla"),entry("diego")]});
assert.deepEqual([...p.jsonUsers(followers,"followers")].sort(),["ana","beto","carla"]);
assert.deepEqual([...p.jsonUsers(following,"following")].sort(),["beto","carla","diego"]);
const v=p.classify(p.jsonUsers(followers,"followers"),p.jsonUsers(following,"following"));
assert.deepEqual(v.mutual.sort(),["beto","carla"]);
assert.deepEqual(v.notFollowingBack,["diego"]);
assert.deepEqual(v.youDontFollow,["ana"]);
assert.equal(p.kindFor("instagram-user/connections/followers_and_following/followers_2.json"),"followers");
assert.equal(p.kindFor("instagram-user/connections/followers_and_following/following.json"),"following");
assert.equal(p.kindFor("close_friends.json"),"");
assert.equal(p.fromHref("https://phishing.example/ana"),"");
assert.equal(p.normalize("Beto"),"beto");
assert.throws(()=>p.jsonUsers('{"relationships_following":[]}',"followers"),/no reconocida/);
const dated='<h1>Seguidores</h1>Contiene los datos que has solicitado desde <time datetime="2026-09-19T03:49Z">18 de septiembre de 2026</time> <time datetime="2025-09-19T03:31Z">18 de septiembre de 2025</time> hasta <time datetime="2026-09-19T03:31Z">18 de septiembre de 2026</time>';
const period=p.htmlExportPeriod(dated);
assert.equal(period.limited,true);
assert.equal(period.from,"18 de septiembre de 2025");
assert.equal(period.to,"18 de septiembre de 2026");
assert.equal(p.htmlExportPeriod("<p>sin fechas</p>"),null);
console.log("PASS: parser, múltiples partes, clasificación, rutas, intervalo acotado y JSON inválido");
